INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');
INSERT INTO BOARD (BOARD_NUM, TITLE, CONTENT, WRITER, IS_PRIVATE) VALUES ((SELECT NVL(MAX(BOARD_NUM), 0) + 1 FROM BOARD), '제목입니다', '내용입니다', 'admin', 'N');


SELECT * FROM EMP;

SELECT EMPNO, ENAME, SAL
FROM EMP;

SELECT EMPNO, ENAME
FROM
(
    SELECT EMPNO, ENAME, SAL AS AAA
    FROM EMP
    WHERE EMPNO < (SELECT MAX(EMPNO) FROM EMP)
)
WHERE EMPNO > 1006;

--ROWNUM : 조회된 데이터에 행 번호를 부여
-- ORDER BY 실행 전에 순서가 부여
SELECT ROWNUM, EMPNO, ENAME, SAL
FROM EMP
ORDER BY SAL DESC;

-- 정렬이 된 상태에서 ROWNUM을 부여하는 방법
SELECT EMPNO, ENAME, SAL
FROM EMP;

SELECT ROWNUM, EMPNO, ENAME, SAL
FROM
(
    SELECT EMPNO, ENAME, SAL
    FROM EMP
    ORDER BY SAL DESC
);


SELECT BOARD_NUM
    , TITLE
    , WRITER
    , CREATE_DATE
    , READ_CNT
    , ATTACHED_NAME
    , ROWNUM
FROM
(
    SELECT BOARD_NUM
    , TITLE
    , WRITER
    , CREATE_DATE
    , READ_CNT
    , ATTACHED_NAME
    FROM BOARD
    ORDER BY BOARD_NUM DESC
);



--


SELECT BOARD_NUM
    , TITLE
    , WRITER
    , CREATE_DATE
    , READ_CNT
    , ATTACHED_NAME
    , ROW_NUM
FROM
(
    SELECT BOARD_NUM
    , TITLE
    , WRITER
    , CREATE_DATE
    , READ_CNT
    , ATTACHED_NAME
    , ROWNUM AS ROW_NUM
    FROM
    (
        SELECT BOARD_NUM
        , TITLE
        , WRITER
        , CREATE_DATE
        , READ_CNT
        , ATTACHED_NAME
        FROM BOARD
        ORDER BY BOARD_NUM DESC
    )
)
WHERE ROW_NUM >=11 AND ROW_NUM <= 20;

SELECT COUNT(BOARD_NUM) FROM BOARD;
