--1.
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP;

--2.
SELECT ENAME, SAL, SAL*12 AS 연봉
FROM EMP;

--3.
SELECT EMPNO, ENAME, SAL, COMM
FROM EMP
WHERE COMM IS NOT NULL;

--4.
SELECT EMPNO, ENAME, SAL, HIREDATE
FROM EMP
WHERE SAL >= 500;

--5.
SELECT EMPNO, ENAME, SAL, COMM
FROM EMP
WHERE SAL >= 300 AND SAL <= 1000 AND COMM IS NULL;

--6.
SELECT *
FROM EMP
WHERE DEPTNO != 30
ORDER BY ENAME ASC;

--7.
SELECT EMPNO, ENAME
FROM EMP
WHERE ENAME LIKE '김__' OR ENAME LIKE '%기%';

--8.
SELECT ENAME, COMM, HIREDATE
FROM EMP
WHERE COMM IS NOT NULL AND HIREDATE > '20021009'
ORDER BY HIREDATE DESC;

--9.
UPDATE EMP
SET
SAL = SAL + (SAL * 0.1)
WHERE DEPTNO = 30;

--10.
SELECT DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.ENAME = '이문세';
