ALTER SESSION SET "_ORACLE_SCRIPT" = true;

--계정 생성 ID : MYDB / PW : oracle
CREATE USER MYDB IDENTIFIED BY oracle;


GRANT CONNECT, RESOURCE TO MYDB;

ALTER USER MYDB DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;