-- 함수
-- DECODE 함수 -> 자바로 따지면 약간 IF문 같은 개념
-- EMP 테이블에서 부서번호가 10이면 '개발부'
-- 20이면 '영업부'를 출력해보세요.
SELECT DEPTNO
    , DECODE(DEPTNO, 10, '개발부', 20, '영업부')
FROM EMP;

-- EMP 테이블에서 부서번호가 10이면 '개발부'
-- 그 외에는 모두 '영업부' 로 조회
SELECT DEPTNO
    , DECODE(DEPTNO, 10, '개발부', '영업부')
FROM EMP;

-- 10이면 개발부, 20이면 영업부, 30이면 인사부
SELECT DEPTNO
    , DECODE(DEPTNO, 10, '개발부', 20, '영업부', 30, '인사부')
FROM EMP;

-- 그룹함수 MAX()
-- 단일행함수 : 행이 10개 함수를 사용하면 결과도 10개 나옴
-- * 단일행함수와 그룹함수를 동시에 사용할 수 없다!!
SELECT MAX(SAL) FROM EMP;
SELECT ENAME, MAX(SAL) FROM EMP;

SELECT * FROM EMP;
-- 테이블에 저장된 데이터의 개수를 조회
-- NULL은 카운트 되지 않음.
SELECT COUNT(EMPNO) FROM EMP;
SELECT COUNT(COMM) FROM EMP;

-- 급여의 합을 조회
SELECT SUM(SAL) FROM EMP;

-- 모든 사원의 급여의 평균을 조회
SELECT ROUND(SUM(SAL) / COUNT(EMPNO), 2) AS AVG
FROM EMP;

SELECT AVG(SAL) FROM EMP;
SELECT AVG(COMM) FROM EMP; -- 380/4 10개가 NULL이라서 잘못나옴
SELECT AVG(NVL(COMM, 0)) FROM EMP; -- 380/14

SELECT * FROM EMP;
-- 입사월이 02월인 사원들의 모든 정보 조회
SELECT * 
FROM EMP
WHERE SUBSTR(HIREDATE, 4, 2) = 2;

SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE, 'MM') = '02'; -- 07/02/03

SELECT *
FROM REPLY;

DELETE REPLY;
COMMIT;

SELECT * FROM REPLY; --REPLY_001, REPLY_002



CREATE TABLE REPLY2 (
    REPLY_NUM VARCHAR2(100) PRIMARY KEY
    , CONTENT VARCHAR2(500) NOT NULL
    , WRITER VARCHAR2(100) REFERENCES BOARD_MEMBER (MEM_ID) 
      ON DELETE CASCADE NOT NULL
    , CREATE_DATE DATE DEFAULT SYSDATE
    , BOARD_NUM NUMBER REFERENCES BOARD (BOARD_NUM) NOT NULL
);


INSERT INTO REPLY2 VALUES ('REPLY_002', '내용입니다.', 'admin', SYSDATE, 1);

SELECT * FROM REPLY2;
-- REPLY_001  -> REPLY_002
SELECT REPLY_NUM FROM REPLY2;

SELECT SUBSTR(REPLY_NUM, 7, 3) FROM REPLY2;
SELECT TO_NUMBER(SUBSTR(REPLY_NUM, 7, 3)) FROM REPLY2;
SELECT NVL(MAX(TO_NUMBER(SUBSTR(REPLY_NUM, 7, 3))), 0) + 1 FROM REPLY2;
SELECT LPAD(NVL(MAX(TO_NUMBER(SUBSTR(REPLY_NUM, 7, 3))), 0) + 1, 3, '0') FROM REPLY2;
SELECT 'REPLY_'||LPAD(NVL(MAX(TO_NUMBER(SUBSTR(REPLY_NUM, 7, 3))), 0) + 1, 3, '0') FROM REPLY2;

DELETE REPLY2;