-- 함수
-- DECODE 함수 -> 자바로 따지면 약간 IF문 같은 개념
-- EMP 테이블에서 부서번호가 10이면 '개발부'
-- 20이면 '영업부'를 출력해보세요.
SELECT DEPTNO
    , DECODE(DEPTNO, 10, '개발부', 20, '영업부')
FROM EMP;

-- EMP 테이블에서 부서번호가 10이면 '개발부'
-- 그 외에는 모두 '영업부' 로 조회
SELECT DEPTNO
    , DECODE(DEPTNO, 10, '개발부', '영업부')
FROM EMP;

-- 10이면 개발부, 20이면 영업부, 30이면 인사부
SELECT DEPTNO
    , DECODE(DEPTNO, 10, '개발부', 20, '영업부', 30, '인사부')
FROM EMP;

-- 그룹함수 MAX()
-- 단일행함수 : 행이 10개 함수를 사용하면 결과도 10개 나옴
-- * 단일행함수와 그룹함수를 동시에 사용할 수 없다!!
SELECT MAX(SAL) FROM EMP;
SELECT ENAME, MAX(SAL) FROM EMP;

SELECT * FROM EMP;
-- 테이블에 저장된 데이터의 개수를 조회
-- NULL은 카운트 되지 않음.
SELECT COUNT(EMPNO) FROM EMP;
SELECT COUNT(COMM) FROM EMP;

-- 급여의 합을 조회
SELECT SUM(SAL) FROM EMP;

-- 모든 사원의 급여의 평균을 조회
SELECT ROUND(SUM(SAL) / COUNT(EMPNO), 2) AS AVG
FROM EMP;

SELECT AVG(SAL) FROM EMP;
SELECT AVG(COMM) FROM EMP; -- 380/4 10개가 NULL이라서 잘못나옴
SELECT AVG(NVL(COMM, 0)) FROM EMP; -- 380/14

SELECT * FROM EMP;
-- 입사월이 02월인 사원들의 모든 정보 조회
SELECT * 
FROM EMP
WHERE SUBSTR(HIREDATE, 4, 2) = 2;

SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE, 'MM') = '02'; -- 07/02/03

SELECT *
FROM REPLY;

DELETE REPLY;
COMMIT;

SELECT * FROM REPLY; --REPLY_001, REPLY_002



CREATE TABLE REPLY2 (
    REPLY_NUM VARCHAR2(100) PRIMARY KEY
    , CONTENT VARCHAR2(500) NOT NULL
    , WRITER VARCHAR2(100) REFERENCES BOARD_MEMBER (MEM_ID) 
      ON DELETE CASCADE NOT NULL
    , CREATE_DATE DATE DEFAULT SYSDATE
    , BOARD_NUM NUMBER REFERENCES BOARD (BOARD_NUM) NOT NULL
);


INSERT INTO REPLY2 VALUES ('REPLY_002', '내용입니다.', 'admin', SYSDATE, 1);

SELECT * FROM REPLY2;
-- REPLY_001  -> REPLY_002
SELECT REPLY_NUM FROM REPLY2;

SELECT SUBSTR(REPLY_NUM, 7, 3) FROM REPLY2;
SELECT TO_NUMBER(SUBSTR(REPLY_NUM, 7, 3)) FROM REPLY2;
SELECT NVL(MAX(TO_NUMBER(SUBSTR(REPLY_NUM, 7, 3))), 0) + 1 FROM REPLY2;
SELECT LPAD(NVL(MAX(TO_NUMBER(SUBSTR(REPLY_NUM, 7, 3))), 0) + 1, 3, '0') FROM REPLY2;
SELECT 'REPLY_'||LPAD(NVL(MAX(TO_NUMBER(SUBSTR(REPLY_NUM, 7, 3))), 0) + 1, 3, '0') FROM REPLY2;

DELETE REPLY2;

-- GROUP BY 절
-- 부서번호 별로 각 부서별 부서인원의 급여 합계를 조회
SELECT DEPTNO, SUM(SAL)
FROM EMP
GROUP BY DEPTNO;

-- 직급별로 각 직급의 급여의 평균과 인원수를 조회
SELECT JOB, AVG(SAL), COUNT(EMPNO)
FROM EMP
GROUP BY JOB;

-- 부서별 급여의 합을 구하는데 부서번호가 10번인 부서는 제외
-- 부서번호 기준 오름차순 정렬
SELECT DEPTNO, SUM(SAL)
FROM EMP
WHERE DEPTNO != 10
GROUP BY DEPTNO
ORDER BY DEPTNO ASC;

-- 부서별 급여의 합을 구하는데, 부서번호가 10이 아니고, 부서별 급여의 합이 2000이상인
-- 부서의 데이터만 조회, 부서번호기준 오름차순 정렬

SELECT DEPTNO, SUM(SAL)
FROM EMP
WHERE DEPTNO != 10
GROUP BY DEPTNO
HAVING SUM(SAL) >= 2000
ORDER BY DEPTNO ASC;

-- 1. 모든 사원의 급여 최고액, 급여 최저액, 총액 및 평균 급여를 조회
-- 단 평균은 반올림하여 정수로 표현하세요
SELECT MAX(SAL), MIN(SAL), SUM(SAL), ROUND(AVG(SAL), 0)
FROM EMP;

-- 2. 직급별 평균 급여 및 평균 커미션을 조회하되,
--    평균 급여 기준 내림차순 정렬
-- 카운팅 할때 NULL 값을 안세기 때문에 NVL 써줘야한다.
SELECT JOB, AVG(SAL), AVG(NVL(COMM, 0))
FROM EMP
GROUP BY JOB
ORDER BY AVG(SAL) DESC;

-- 3. 급여 최고액과 최저액의 차이를 조회
SELECT MAX(SAL) - MIN(SAL) AS 최고액최저액차이
FROM EMP;
